import "./globals.css";
import Header from "@/_components/Header";
import Footer from "@/_components/Footer";

export const metadata = {
  title: "인생은 모르니까, 전화운세 - 홍카페",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-[72rem] w-[100%] min-h-[100dvh] mx-[auto] border-r border-l border-solid border-[#eee] pb-[7.4rem]">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
